#! /bin/bash
#sudo ./miners/trex/t-rex -a etchash --coin etс -o stratum+ssl://eu.ezil.me:24443  -o stratum+ssl://ro.ezil.me:24443  -u 0x22133b9beef2ecdf5f16950538675925d5da8249.zil1nr5a0c5svt32yljue67phw76lcxj9sr7mrl4nd -w profitswitch --extra-dag-epoch 0
sudo ./miners/lolminer/lolMiner --algo ETHASH --pool eu.crazypool.org:5005 --user zil1nr5a0c5svt32yljue67phw76lcxj9sr7mrl4nd --worker profitswitch --enablezilcache
