#! /bin/bash
card0=$(readlink -f /sys/class/drm/card0/device)
card1=$(readlink -f /sys/class/drm/card1/device)
card2=$(readlink -f /sys/class/drm/card2/device)

sudo sh -c "echo 166000000 > /sys/class/drm/card0/device/hwmon/hwmon0/power1_cap"
sudo sh -c "echo 166000000 > /sys/class/drm/card1/device/hwmon/hwmon1/power1_cap"
#sudo sh -c "echo 135000000 > /sys/class/drm/card2/device/hwmon/hwmon2/power1_cap"


sudo sh -c "echo 'm 1 1040' > $card0/pp_od_clk_voltage"

sudo sh -c "echo 's 1 1220' > $card0/pp_od_clk_voltage"

sudo sh -c "echo 'c' > $card0/pp_od_clk_voltage"

sudo sh -c "echo 'm 1 1040' > $card1/pp_od_clk_voltage"

sudo sh -c "echo 's 1 1220' > $card1/pp_od_clk_voltage"

sudo sh -c "echo 'c' > $card1/pp_od_clk_voltage"
